repos:
- repo: https://github.com/alan-turing-institute/CleverCSV-pre-commit
  rev: v0.6.6
  hooks:
  - id: clevercsv-standardize
    stages: [pre-commit]
- repo: git@github.com:Yelp/detect-secrets
  rev: v1.1.0
  hooks:
  - id: detect-secrets
    stages: [pre-commit]
    args:
      - "--exclude-files"
      - "go.sum"
- repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook
  rev: v2.2.0
  hooks:
  - id: commitlint
    stages: [commit-msg]
    additional_dependencies: ['@commitlint/config-conventional']
